### ISSUE TITLE
Cannot get sidecar to fully sync on Holesky

### ISSUE THREAD

**Issue by ahmohamed** [Layr-Labs/sidecar#264]
As per the title, I've been trying to get sidecar (3.0.0-rc.7) to sync after restoring from the snapshot (22-01-2025) with no luck. Aside from constantly stopping and restarting, I've faced the following show-stopper:

```
{"level":"error","ts":"2025-02-25T03:45:31.064+1100","caller":"pipeline/pipeline.go:423","msg":"Failed to run pipeline for fetched block","blockNumber":3224863,"error":"roots do not match","stacktrace":"github.com/Layr-Labs/sidecar/pkg/pipeline.(*Pipeline).RunForBlockBatch\n\t/build/pkg/pipeline/pipeline.go:423\ngithub.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).IndexFromCurrentToTip\n\t/build/pkg/sidecar/blockIndexer.go:292\ngithub.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).StartIndexing\n\t/build/pkg/sidecar/blockIndexer.go:25\ngithub.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).Start\n\t/build/pkg/sidecar/sidecar.go:82"}
{"level":"error","ts":"2025-02-25T03:45:31.064+1100","caller":"sidecar/blockIndexer.go:293","msg":"Failed to run pipeline for block batch","error":"roots do not match","startBlock":3224863,"batchEndBlock":3224963,"stacktrace":"github.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).IndexFromCurrentToTip\n\t/build/pkg/sidecar/blockIndexer.go:293\ngithub.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).StartIndexing\n\t/build/pkg/sidecar/blockIndexer.go:25\ngithub.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).Start\n\t/build/pkg/sidecar/sidecar.go:82"}
```

When I tried to bypass by rerunning with `--rewards.validate_rewards_root=false`, I got:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x100899bec]

goroutine 109 [running]:
github.com/Layr-Labs/sidecar/pkg/fetcher.(*Fetcher).FetchBlocks(0x1400024e888, {0x101411fe0, 0x101d62ea0}, 0x313dcd, 0x313e31)
        /build/pkg/fetcher/fetcher.go:169 +0x52c
github.com/Layr-Labs/sidecar/pkg/fetcher.(*Fetcher).FetchBlocksWithRetries(0x1400024e888, {0x101411fe0, 0x101d62ea0}, 0x313dcd, 0x313e31)
        /build/pkg/fetcher/fetcher.go:110 +0x284
github.com/Layr-Labs/sidecar/pkg/pipeline.(*Pipeline).RunForBlockBatch(0x140002f35e0, {0x101411fe0, 0x101d62ea0}, 0x313dcd, 0x313e31, 0x1)
        /build/pkg/pipeline/pipeline.go:410 +0x184
github.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).IndexFromCurrentToTip(0x140002f3c70, {0x101411fe0, 0x101d62ea0})
        /build/pkg/sidecar/blockIndexer.go:292 +0x154c
github.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).StartIndexing(0x140002f3c70, {0x101411fe0, 0x101d62ea0})
        /build/pkg/sidecar/blockIndexer.go:25 +0x30
github.com/Layr-Labs/sidecar/pkg/sidecar.(*Sidecar).Start(0x140002f3c70, {0x101411fe0, 0x101d62ea0})
        /build/pkg/sidecar/sidecar.go:82 +0x98
created by github.com/Layr-Labs/sidecar/cmd.init.func6 in goroutine 1
        /build/cmd/run.go:174 +0x19a8
```

(Unrelated question: Do you have a public sidecar RPC?)

**Comment by seanmcgary** [comment]
Hi @ahmohamed - happy to help you debug this. Could you reply with how you're running the sidecar? I want to just double check your runtime flags/params so I can try to reproduce it.

We do actually have a public RPC that's in beta right now and has a few of the RPC routes available. What data/routes are you looking for currently?

**Comment by damon-pk** [comment]
> Hi [@ahmohamed](https://github.com/ahmohamed) - happy to help you debug this. Could you reply with how you're running the sidecar? I want to just double check your runtime flags/params so I can try to reproduce it.
> 
> We do actually have a public RPC that's in beta right now and has a few of the RPC routes available. What data/routes are you looking for currently?

hi, seanmcgary, can you share the public RPC in private, We are now running the sidecar service, but can't sync the historic data, tried for a few days.

**Comment by ahmohamed** [comment]
Thanks @seanmcgary for your response. 
Let me answer your second question first, as we might be interested in the public RPC as a quick short-term solution while we get ours up and running.

So basically, we are after reward proofs. Using a sidecar client  as defined here (https://github.com/Layr-Labs/protocol-apis), we are using the following API functions:
- ListDistributionRoots
- GetSummarizedRewardsForEarner
- GenerateClaimProof

Which is the minimum to fetch rewards and generate reward proofs. It would be great to on-board us with your public beta RPC, so we can ship this functionality. There is a `Attestant <> Eigen Labs` telegram group that we can use for private comms.


Now back to the main issue, the full story is as follows:
- Ran postgres in docker.
- Downloaded Holesky snapshot.
- Downloaded sidecar binary (Darwin-arm64). This was done with V3.0-rc.1.
- Restored snapshot as per docs.
- Tried syncing, but it was not indexing at all.
- rc.7 was released, so downloaded that and ran using this command:

```bash
./sidecar run \
    --ethereum.rpc-url=https://ethereum-holesky-rpc.publicnode.com/ \
    --chain="holesky" \
    --database.host="localhost" \
    --database.port="5432" \
    --database.user="sidecar" \
    --database.password="sidecar" \
    --database.db_name="sidecar"
```

- Started indexing and progressed through blocks with occasionally erroring:
```
{"level":"error","ts":"2025-02-26T13:56:10.551Z","caller":"sequentialContractCaller/contractCaller.go:129","msg":"getOperatorRestakedStrategiesBatch - failed to get results","avs":"0x20864c431f751aabc3d5828ba85cec3bab3c37c6","operator":"0x1b6dbf8213a1c6b7a18b7a97be1e0f3a171af7d2","blockNumber":3301200,"error":"missing trie node 4b8459a5ee115ac10bd7b8462484e7a34c03893d10def276603c792c0d74d1c9 (path ) state 0x4b8459a5ee115ac10bd7b8462484e7a34c03893d10def276603c792c0d74d1c9 is not available","stacktrace":"github.com/Layr-Labs/sidecar/pkg/contractCaller/sequentialContractCaller.(*SequentialContractCaller).getOperatorRestakedStrategiesBatch.func1\n\t/build/pkg/contractCaller/sequentialContractCaller/contractCaller.go:129"}
```

- The error would go away after some time.
- Eventually, we hit the `"roots do not match"` error, so we started running without root validation.
- Started seeing the panics above.
- Currently, I'm running sidecar using the config below so allow it to restart after panics.

```
version: '3.8'

services:
  sidecar:
    # image: public.ecr.aws/z6g0f8n7/sidecar:latest run
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "run"
    ports:
      - "7200:7200"
      - "7201:7201"
    environment:
      - SIDECAR_DEBUG=false
      - SIDECAR_ETHEREUM_RPC_URL=https://ethereum-holesky-rpc.publicnode.com/
      - SIDECAR_CHAIN=holesky
      # - SIDECAR_STATSD_URL=localhost:8125
      - SIDECAR_DATABASE_HOST=host.docker.internal
      - SIDECAR_DATABASE_PORT=5432
      - SIDECAR_DATABASE_USER=sidecar
      - SIDECAR_DATABASE_PASSWORD=sidecar
      - SIDECAR_DATABASE_DB_NAME=sidecar
      - SIDECAR_ETHEREUM_USE_NATIVE_BATCH_CALL=true
      - SIDECAR_ETHEREUM_NATIVE_BATCH_SIZE=100
      - SIDECAR_RPC_GRPC_PORT=7200
      - SIDECAR_RPC_HTTP_PORT=7201
      - SIDECAR_REWARDS_VALIDATE_REWARDS_ROOT=false
    restart: unless-stopped
```

- Current status, moving slowly towards syncing. 120k blocks left.
